In [1]:
#Q3

In [2]:
import numpy as np
np.random.seed(42)
A = np.random.randint(0, 10, size=(5, 5)) # Create a 5x5 matrix with random integers between 0 and 9
print("Matrix A:")
print(A)
print()

Matrix A:
[[6 3 7 4 6]
 [9 2 6 7 4]
 [3 7 7 2 5]
 [4 1 7 5 1]
 [4 0 9 5 8]]



In [3]:
U, Sigma, VT = np.linalg.svd(A)

In [4]:
print("Matrix U:")
print(U)
print()

Matrix U:
[[-0.46659592  0.10065472 -0.02287376  0.32537883 -0.81594257]
 [-0.501475   -0.53162269 -0.44588159  0.35524809  0.37535123]
 [-0.39771671  0.79009347 -0.34775324 -0.11898872  0.2871987 ]
 [-0.34525211 -0.28793584 -0.11189547 -0.8675511  -0.18090999]
 [-0.50342177  0.00954962  0.81683137  0.03352891  0.27953113]]



In [5]:
print("Matrix Sigma:")
print(np.diag(Sigma))
print()

Matrix Sigma:
[[25.72194822  0.          0.          0.          0.        ]
 [ 0.          6.67758506  0.          0.          0.        ]
 [ 0.          0.          5.2344033   0.          0.        ]
 [ 0.          0.          0.          3.47436002  0.        ]
 [ 0.          0.          0.          0.          0.56664098]]



In [6]:
print("Matrix V^T:")
print(VT)
print()

Matrix V^T:
[[-0.46266698 -0.21506951 -0.62229342 -0.40492701 -0.43413062]
 [-0.43787392  0.67111646  0.16711085 -0.46880483  0.33191132]
 [-0.45347919 -0.66990494  0.24807708 -0.07326397  0.52789596]
 [ 0.41919976 -0.00398332 -0.63173596 -0.17840305  0.62716642]
 [-0.46133922  0.23357934 -0.35240928  0.76096051  0.17132896]]



In [7]:
reconstructed_A = U @ np.diag(Sigma) @ VT
print("Is A equal to the product of U, Sigma, and V^T?")
print(np.allclose(A, reconstructed_A))
print()

Is A equal to the product of U, Sigma, and V^T?
True



In [8]:
rank_2_approx = U[:, :2] @ np.diag(Sigma[:2]) @ VT[:2, :]
print("Rank 2 approximation of A:")
print(rank_2_approx)
print()

Rank 2 approximation of A:
[[5.25850785 3.03228961 7.58093409 4.54473715 5.43341749]
 [7.52233457 0.39172935 7.43367305 6.88735495 4.42154296]
 [2.42291947 5.74092586 7.24775476 1.66904786 6.19231366]
 [4.95064771 0.61957065 5.20500544 4.49735592 3.21715048]
 [5.96314695 2.82772869 8.0687268  5.21350025 5.64271791]]



In [9]:
rank_3_approx = U[:, :3] @ np.diag(Sigma[:3]) @ VT[:3, :]
print("Rank 3 approximation of A:")
print(rank_3_approx)

Rank 3 approximation of A:
[[ 5.31280314  3.11249766  7.5512317   4.55350908  5.37021223]
 [ 8.58072057  1.9552366   6.85467998  7.05834748  3.18947387]
 [ 3.2483789   6.9603409   6.79618483  1.80240885  5.23139483]
 [ 5.2162532   1.011938    5.0597052   4.54026706  2.90795864]
 [ 4.02424005 -0.03653349  9.12941132  4.90025102  7.89980299]]
