In [1]:
import numpy as np
import sympy as sp

In [21]:
np.random.seed(42)
A=np.random.randint(0, 10, (5,5))
print ("Matrix A:")
print(A)

Matrix A:
[[6 3 7 4 6]
 [9 2 6 7 4]
 [3 7 7 2 5]
 [4 1 7 5 1]
 [4 0 9 5 8]]


In [3]:
A=np.array([[6,3,7,4,6], [9,2,6,7,4], [3,7,7,2,5], [4,1,7,5,1], [4,0,9,5,8]])

In [4]:
A[0]=A[0]/6
A[0]

array([1, 0, 1, 0, 1])

In [5]:
A[1]=A[1]-A[0]*9
A[1]

array([ 0,  2, -3,  7, -5])

In [6]:
A[2]=A[2]-A[0]*3
A[2]

array([0, 7, 4, 2, 2])

In [7]:
A[3]=A[3]-A[0]*4
A[3]

array([ 0,  1,  3,  5, -3])

In [8]:
A[4]=A[4]-A[0]*4
A[4]

array([0, 0, 5, 5, 4])

In [25]:
A

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5],
       [4, 1, 7, 5, 1],
       [4, 0, 9, 5, 8]])

In [9]:
A[1]=A[1]/2
A[1]

array([ 0,  1, -1,  3, -2])

In [10]:
A[2]=A[2]-A[1]*7
A[2]

array([  0,   0,  11, -19,  16])

In [11]:
A[3]=A[3]-A[1]
A[3]

array([ 0,  0,  4,  2, -1])

In [ ]:
A

In [12]:
A[2]=A[2]/11
A[2]

array([ 0,  0,  1, -1,  1])

In [13]:
A[3]=A[3]-A[2]*4
A[3]

array([ 0,  0,  0,  6, -5])

In [14]:
A[4]=A[4]-A[2]*5
A[4]

array([ 0,  0,  0, 10, -1])

In [15]:
A

array([[ 1,  0,  1,  0,  1],
       [ 0,  1, -1,  3, -2],
       [ 0,  0,  1, -1,  1],
       [ 0,  0,  0,  6, -5],
       [ 0,  0,  0, 10, -1]])

In [16]:
A[3]=A[3]/6
A[3]

array([0, 0, 0, 1, 0])

In [17]:
A[4]=A[4]-A[3]*10
A[4]

array([ 0,  0,  0,  0, -1])

In [ ]:
A

In [26]:
A[4]=A[4]/(-1)
A[4]

array([-4,  0, -9, -5, -8])

In [ ]:
A